### ISSUE TITLE
Django Tutorial

### ISSUE THREAD

**Issue by mehmeteyupoglu** [mehmeteyupoglu/swe573#14]
- [ ] Read the documentation
- [ ] Find a short tutorial to begin with
- [ ] Learn the differences b/w Django and Django Rest

**Comment by uskudarli** [comment]
DjangoREST is for API based development.

Django is an MVC based framework.

**Comment by mehmeteyupoglu** [comment]
I worked with Node Express.js on an MVC architecture. In this case, the same architecture could be created with Django.
